CREATE TABLE cancha (
    id_cancha BIGINT AUTO_INCREMENT PRIMARY KEY,
    s_nombre VARCHAR(100) NOT NULL
);

ALTER TABLE clase
ADD COLUMN id_cancha BIGINT;

ALTER TABLE clase
ADD CONSTRAINT fk_clase_cancha
    FOREIGN KEY (id_cancha)
    REFERENCES cancha (id_cancha)
    ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE usuario
ADD COLUMN fecha_alta TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;