CREATE TABLE IF NOT EXISTS cancha (
    id_cancha     BIGINT AUTO_INCREMENT PRIMARY KEY,
    s_nombre    VARCHAR(100) NOT NULL
);

ALTER TABLE clase
ADD COLUMN IF NOT EXISTS id_cancha BIGINT;

ALTER TABLE clase
ADD CONSTRAINT fk_clase_cancha
    FOREIGN KEY (id_cancha)
    REFERENCES cancha (id_cancha)
    ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE usuario
ADD COLUMN IF NOT EXISTS fecha_alta TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;